name: Move solution to archive help
description: Move an ArcGIS Solution (one or many versions) into Mature Support or Retired Lifecycle.
labels: ["Type: Doc"]
#title: ""
assignees: ["heat5533"]
#projects: ["WebGIS/216"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request to move a solution into Mature Support or Retired Lifecycle. If this doesn’t look right, [choose a different type](https://devtopia.esri.com/WebGIS/solutions-enablement/issues/new/choose).
  - type: input
    id: solution-name
    attributes:
      label: Solution name
      description: Please provide the full solution name.
    validations:
      required: true
  - type: input
    id: mature-phase
    attributes:
      label: Mature Phase Lifecycle
      description: Please provide the release Month \ Year it of the Mature Phase Lifecycle. (Example: November 2023 - October 2025).
    validations:
      required: false
  - type: input
    id: retired-phase
    attributes:
      label: Retired Lifecycle
      description: Please provide the release Month \ Year of the the Retired Lifecycle (2 years after Mature Phase). (Example: November 2025)
    validations:
      required: true
  - type: input
    id: new-solution
    attributes:
      label: Solution replacement
      description: Please provide the new solution name that is replacing the Capabilities of this solution. (if applicable) (For Example: Park Infrastructure Management has been moved to Mature Lifecycle Phase. Capabilities have been replaced with Parks and Grounds Management.)
    validations:
      required: false
  - type: checkboxes
    id: publications
    attributes:
      label: Solution product
      description: Which product is the solution avaliable in?
      options:
      - label: ArcGIS Enterprise 10.9.1
      - label: ArcGIS Enterprise 11
      - label: ArcGIS Enterprise 11.1
      - label: ArcGIS Enterprise 11.2
      - label: ArcGIS Online
    validations:
      required: true
  - type: markdown
    attributes:
      description: Please create a separate issue to remove Solution gallery items from the [ArcGIS Solutions app](https://devtopia.esri.com/WebGIS/solution-items).
