name: Move solution to archive help
description: Move an ArcGIS Solution (one or many versions) into Mature Support or Retired Lifecycle.
labels: ["Type: Doc"]
#title: ""
#assignees: ["heat5533"]
#projects: ["WebGIS/216"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request to move a solution into Mature Support or Retired Lifecycle. Please create a separate issue to remove Solution gallery items from the [ArcGIS Solutions app](https://devtopia.esri.com/WebGIS/solution-items).
  - type: input
    id: solution-name
    attributes:
      label: Solution name
      description: Please provide the full solution name.
    validations:
      required: true
  - type: input
    id: mature-phase
    attributes: |
      label: Mature Phase Lifecycle
      description: Please provide the release Month \ Year it of the Mature Phase Lifecycle. (Example: November 2023 - October 2025).
    validations:
      required: false