name: Upload solution video
description: Add or update a video on Kaltura.
labels: ["Type: Upload video"]
#title: ""
#assignees: ["jai10618"]
#projects: ["WebGIS/216"]
body:
  - type: markdown
    attributes:
      value: |
        Add or update an ArcGIS Solutions video on Kaltura
  - type: input
    id: solution-name
    attributes:
      label: Solution name
      description: Provide the full solution name.
    validations:
      required: true
  - type: checkboxes
    id: video-update
    attributes:
      label: Update or add new video
      description: Check all that apply.
      options:
      - label: Add new video
      - label: Update existing video
    validations:
      required: true
  - type: checkboxes
    id: video-approve
    attributes:
      label: Video approval
      description: Your video must be reviewed and approved by your team lead or Scott prior to upload. What is the approval status of your video?
      options:
      - label: Approved
      - label: Not approved
    validations:
      required: true
  - type: checkboxes
    id: solution-image
    attributes:
      label: Solution image
      description: The original solution item image must be uploaded to the Solution Development > solution [name] folder in Microsoft Teams. What is the upload status of your video?
      options:
      - label: Uploaded
      - label: Not uploaded
    validations:
      required: true