name: Upload solution video
description: Use this template to add or update a video on Kaltura.
labels: ["Type: Upload video"]
#title: ""
#assignees: ["jai10618"]
#projects: ["WebGIS/216"]
body:
  - type: markdown
    attributes:
      value: |
        Add or update an ArcGIS Solution Enablement Video on Kaltura
  - type: input
    id: solution-name
    attributes:
      label: Solution name
      description: Please provide the full solution name.
    validations:
      required: true
  - type: checkboxes
    id: video-update
    attributes:
      label: Update or add new video
      description: Check all that apply.
      options:
      - label: Add new video
      - label: Update existing video
    validations:
      required: true
  - type: checkboxes
    id: video-approved
    attributes:
      label: Video approval
      description: Has the video been reviewed and approved by your team lead or Scott? The video must be reviewed prior to upload.
      - label: Yes
      - label: No
    validations:
      required: true