name: Map review
description: Request a map review.
labels: ["Type: Map Review"]
#title: ""
#assignees: ["jai10618"]
#projects: ["WebGIS/216"]
body:
  - type: markdown
    attributes:
      value: |
        Review and provide feedback on maps. The standard turnaround time for map review and feedback is typically 3-4 business days, but it may vary depending on the complexity of the map and the specific requirements of the project. 
  - type: input
    id: solution-name
    attributes:
      label: Solution name
      description: Provide the full solution name.
    validations:
      required: true
  - type: input
    id: solution-url
    attributes:
      label: Solution URL
      description: Enter the path of the ArcGIS Pro project containing the map you want reviewed or the URL to a webmap or webmaps.
    validations:
      required: true
  - type: input
    id: duedate
    attributes:
      label: Date needed
      description: Completion dates cannot be guaranteed, but all effort will be made to accommodate the requested date. 
      placeholder: |
        dd/mm/yyyy
    validations:
      required: true