name: Blank issue
description: Report an enhancement, bug, or ask a question.
#labels:
#title: ""
assignees: ["jai10618"]
#projects: ["WebGIS/216"]
body:
  - type: textarea
    id: describe-request
    attributes:
      label: Describe the request
      description: A clear description about an enhancement, bug, or ask a question.
    validations:
      required: true
  - type: textarea
    id: relevant
    attributes:
      label: Other relevant info
      description: Add any other context or screenshots or GIFs.
    validations:
      required: false