name: ArcGIS Online and Enterprise Checklist
description: Release Verification Checklist for ArcGIS Online and Enterprise.
labels: ["Type: Doc"]
#title: ""
#assignees: ["heat5533"]
#projects: ["WebGIS/216"]
body:
  - type: input
    id: release-information
    attributes:
      label: Current release information
      value:  
        Please ensure that you have verified the following items for each solution and then mark the corresponding solution name in the checklist below by COB <insert date>.
    validations:
      required: false
  - type: input
    id: latest-information
    attributes:
      label: Current website information
      value:  
        Documentation - Validate ArcGIS Online topics are visible in TOC - https://docstg.arcgis.com/en/arcgis-solutions/latest/reference/
    validations:
      required: false     
  - type: input
    id: enterprise-information
    attributes:
      label: Current ArcGIS Enterprise information
      value:  
        Documentation - Validate ArcGIS Enterprise topics are visible in TOC - https://docstg.arcgis.com/en/arcgis-solutions/11.5/reference/
    validations:
      required: false    
  - type: input
    id: validate-information
    attributes:
      label: Validate contents on the page 
      value:  
        Documentation - Validate all content on page, ArcGIS Enterprise release notes enhancements are present (if applicable), and solution version in app and doc match.
        Solution - Final version deploys correctly
    validations:
      required: false             
  - type: textarea
    id: new-solutions
    attributes:
      label: New solutions
      description: 
    validations:
      required: true
  - type: textarea
    id: enhanced-solutions
    attributes:
      label: Enhanced solutions
      description: 
    validations:
      required: true