name: ArcGIS Online and Enterprise Checklist
description: Release Verification Checklist for ArcGIS Online and Enterprise.
labels: ["Type: Doc"]
#title: ""
#assignees: ["heat5533"]
#projects: ["WebGIS/216"]
body:
  - type: markdown
    attributes:
    label:  
        Use this template to identify the solutions that need verification in the current release.
        Please ensure that you have verified the following items for each solution and then mark the corresponding solution name in the checklist below by COB .
        Validate ArcGIS Online topics are visible in TOC - 
        Validate ArcGIS Enterprise topics are visible in TOC - 
        Validate all content on page
        Validate ArcGIS Enterprise release notes enhancements are present (if applicable)
        Verify solution version in app and doc match
  - type: textarea
    id: new-solutions
    attributes:
      label: New solutions
      description: 
    validations:
      required: true
  - type: textarea
    id: enhanced-solutions
    attributes:
      label: Enhanced solutions
      description: 
    validations:
      required: true