name: ArcGIS Online and Enterprise Checklist
description: Release Verification Checklist for ArcGIS Online and Enterprise.
labels: ["Type: Doc"]
#title: ""
#assignees: ["heat5533"]
#projects: ["WebGIS/216"]
body:
  - type: input
    id: release-information
    attributes:
      label: Current release information
      value:  
        Please ensure that you have verified the following items for each solution and then mark the corresponding solution name in the checklist below by COB <insert date>.
    validations:
      required: false
  - type: textarea
    id: new-solutions
    attributes:
      label: New solutions
      description: 
    validations:
      required: true
  - type: textarea
    id: enhanced-solutions
    attributes:
      label: Enhanced solutions
      description: 
    validations:
      required: true